# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.jwtsecret: '%env(JWT_SECRET)%'
services:
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Form\CommentaireType:
        tags: ['form.type']

    App\Form\BarreDeRechercheAutocomplete:
        tags: ['form.type']

    App\Form\VideoType:
        tags: ['form.type']

    App\Form\UserType:
        tags: ['form.type']

    App\Form\TypeType:
        tags: ['form.type']

    App\Form\ResetPasswordRequestFormType:
        tags: ['form.type']

    App\Form\ResetPasswordFormType:
        tags: ['form.type']

    App\Form\ResearchFilmType:
        tags: ['form.type']

    App\Form\RegistrationFormType:
        tags: ['form.type']

    App\Form\MailType:
        tags: ['form.type']
    
    App\Form\InfoType:
        tags: ['form.type']

    App\Form\CategorieType:
        tags: ['form.type']
      
    App\Form\CategoriePrefType:
        tags: ['form.type']

    App\Form\AbonnementType:
        tags: ['form.type']